services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    command: bin/dev
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules

    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true

volumes:
  node_modules:
