# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { "db" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "postgres" } %>
  pool: 5

development:
  <<: *default
  database: jarvis_development

test:
  <<: *default
  database: jarvis_test

production:
  primary: &primary_production
    <<: *default
    database: jarvis_production
    username: jarvis
    password: <%= ENV["JARVIS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: jarvis_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: jarvis_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: jarvis_production_cable
    migrations_paths: db/cable_migrate
